### PR TITLE
Bug Bash Tweaks: copy update and revise external links

### LINKED ISSUE #219: Misc updates

### PR DESCRIPTION
**Pull request by tarinrickett**
# Summary

Bug Bash Tweaks: Copy update and revise external links

## Issue
Fixes #219

## Description

- Misc. copy updates
- AISF URLs are no longer being treated as external links. Update everywhere.
- Weirdly, CourseCard lint tests were failing because 2 props were mistakenly considered unused. Added eslint disable to resolve for now.

## Developer checklist
- [ ] Used [BEM naming convention](https://getbem.com/naming/) for classNames
- [ ] Added or updated Jest tests
- [ ] Added or updated Storybook stories

## Screenshot

image
image

## Testing
```
$ npm run test:update
<!-- Run `npm run test` from the base `bluedot` dir and include the output here -->
```

### CODE REVIEW

File: apps/website-25/src/components/about/IntroSection.tsx [hunk 1]
```diff
@@ -5,8 +5,8 @@ const IntroSection = ({ title }: { title: string }) => {
...
+          <p>Humanity faces unprecedented challenges from transformative AI (TAI) which could profoundly reshape our future. Current AI systems already exhibit concerning behaviours, and as they become more powerful, misalignment between their actions, human intentions and societal values could lead to catastrophic outcomes.</p>
+          <p>BlueDot Impact exists to safeguard humanity from these risks by building and accelerating the AI safety field.  We’ve trained over 4,000 professionals and helped hundreds land roles at organisations like Anthropic and the UK’s AI Safety Institute. We’ve built a strong foundation of,  deep knowledge in how to communicate complex concepts, close relationships across the field and expertise in talent development. However, urgency and the magnitude of AI risk demands we do much more.</p>
```
Comment (Will-Howard) [inline apps/website-25/src/components/about/IntroSection.tsx:9]: `We’ve built a strong foundation of,  deep knowledge`
^This seems like a typo?

**Review by Will-Howard — APPROVED** [review]
Looks good apart from that one typo

File: apps/website-25/src/components/about/IntroSection.tsx (hunk 1 above)
Comment (tarinrickett) [reply apps/website-25/src/components/about/IntroSection.tsx]: great catch, thank you !!! highlighted it for the copy team as well
