### PR TITLE
`CourseListRow` test mock time

### LINKED ISSUE #1367: [Bug] Fix CourseListRow.tsx test to use mock time
### 🧩 Summary

Currently, I think whenever somebody runs ```npm run test --u`` with a north american timezone, you will update the ``courseListRow` snapshot to be Dec 31, 2023 instead of Jan 1, 2024.

This will cause in ci-cd to fail because it's using a different timezone despite it passing locally. 

### 🛝 Steps to reproduce

Set your computer clock to a north american timezone (say PST), and run snapshots. I think you should get courseListRow's snapshot to be updated despite not making any code changes.

### ✅ Definition of done

Anyone can run snapshots without needing to revert ```courseListRow``'s snapshot. 

### 📌 Notes / Designs

_No response_

### Suggested Priority Level

{"P2" => "Medium (Default)"}

### PR DESCRIPTION
**Pull request by joshestein**
## Issue

Fixes #1367.

## Developer checklist

- [x] Front-end code follows [Component Accessibility Checklist (for Testing)](https://github.com/bluedotimpact/bluedot/blob/master/DEVELOPMENT_HANDBOOK.md#component-accessibility-checklist)
- [x] Considered having snapshot tests and/or happy path functional tests
- [x] Considered adding Storybook stories

## Screenshot

NA

### CODE REVIEW

File: apps/website/src/__tests__/testUtils.ts [hunk 1]
```diff
@@ -10,16 +12,15 @@ export const mockCourse = (overrides: Partial<Course>): Course => ({
...
   image: '/images/courses/default.jpg',
-  slug: 'course-slug',
+  isFeatured: false,
+  isNew: false,
+  level: 'Beginner',
   path: '/courses/course-slug',
+  publicLastUpdated: null,
   shortDescription: 'Short description',
+  slug: 'course-slug',
+  status: 'published',
```
Comment (joshestein) [inline apps/website/src/__tests__/testUtils.ts:22]: `status` was missing causing a type error. Everything else I just alphabetised.

File: apps/website/src/components/settings/CourseListRow.test.tsx [hunk 2]
```diff
@@ -51,6 +60,23 @@ describe('CourseListRow', () => {
...
+  beforeEach(() => {
+    vi.useFakeTimers();
+    vi.setSystemTime(new Date('2024-01-01'));
+
+    // Mock the API call for meet person data
+    vi.mocked(useAxios).mockReturnValue([{
+      data: null,
+      loading: false,
+      error: null,
+    }, () => {}, () => {}] as unknown as ReturnType<typeof useAxios>);
```
Comment (joshestein) [inline apps/website/src/components/settings/CourseListRow.test.tsx:72]: idk mocking time was causing request to fail so I needed to mock axios as well. This was copied from `CourseDetails.test.tsx`

File: apps/website/src/components/settings/CourseListRow.test.tsx [hunk 3]
```diff
@@ -126,7 +152,7 @@ describe('CourseListRow', () => {
   });
 
   it('collapses and expands course details', async () => {
-    const user = userEvent.setup();
+    const user = userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
```
Comment (joshestein) [inline apps/website/src/components/settings/CourseListRow.test.tsx:155]: the test was failing without this, see https://github.com/testing-library/user-event/issues/1115

**Comment by joshestein** [comment]
@marn-in-prod ignore previous request, this is not working, my bad.
